-- Supabase Schema Initialization Script for Job Application CRM Cloud
-- Run this script in the Supabase SQL Editor to prepare your database for syncing.

-- 1. Create Tables

CREATE TABLE IF NOT EXISTS public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  website text,
  logo_url text,
  dark_logo_bg boolean default false,
  industry text,
  financial_stability_warning boolean default false,
  notes text,
  last_interaction timestamp with time zone default now(),
  user_id uuid references auth.users not null,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.jobs (
  id bigint generated by default as identity primary key,
  company_id bigint references public.companies on delete cascade,
  title text not null,
  body text,
  status text not null,
  salary text,
  description text,
  url text,
  location text,
  fit_score integer default 3,
  user_id uuid references auth.users not null,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  company_id bigint references public.companies on delete cascade,
  job_id bigint references public.jobs on delete cascade,
  role text,
  email text,
  phone text,
  notes text,
  linkedin_url text,
  next_check_in timestamp with time zone,
  social_platform text,
  social_handle text,
  email_draft text,
  is_prospective integer default 0,
  last_interaction timestamp with time zone default now(),
  user_id uuid references auth.users not null,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.interactions (
  id bigint generated by default as identity primary key,
  job_id bigint references public.jobs on delete cascade,
  contact_id bigint references public.contacts on delete cascade,
  company_id bigint references public.companies on delete cascade,
  type text,
  content text,
  date timestamp with time zone default now(),
  user_id uuid references auth.users not null,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.reminders (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id bigint not null,
  source text not null default 'manual',
  due_at timestamp with time zone not null,
  message text not null,
  link_path text,
  notify_desktop integer default 1,
  notify_email integer default 0,
  contact_id bigint references public.contacts on delete cascade,
  sent_at timestamp with time zone,
  user_id uuid references auth.users not null,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  reminder_id bigint references public.reminders on delete cascade,
  entity_type text not null,
  entity_id bigint not null,
  due_at timestamp with time zone not null,
  title text,
  message text not null,
  link_path text,
  notify_desktop integer default 1,
  notify_email integer default 0,
  logo_url text,
  icon_bg text,
  delivered_desktop_at timestamp with time zone,
  delivered_email_at timestamp with time zone,
  read_at timestamp with time zone,
  dismissed_at timestamp with time zone,
  user_id uuid references auth.users not null,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.documents (
  id bigint generated by default as identity primary key,
  job_id bigint references public.jobs on delete cascade,
  filename text not null,
  path text not null,
  type text,
  user_id uuid references auth.users not null,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.interview_questions (
  id bigint generated by default as identity primary key,
  type text not null,
  question text not null,
  answer text,
  user_id uuid references auth.users not null,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);

-- 2. Configure Row Level Security (RLS)

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interview_questions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only access their own companies" ON public.companies FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can only access their own jobs" ON public.jobs FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can only access their own contacts" ON public.contacts FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can only access their own interactions" ON public.interactions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can only access their own reminders" ON public.reminders FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can only access their own notifications" ON public.notifications FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can only access their own documents" ON public.documents FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users can only access their own interview questions" ON public.interview_questions FOR ALL USING (auth.uid() = user_id);

-- 3. Configure Storage
-- Note: Supabase Storage buckets cannot be created purely via SQL in some cases, 
-- but we can set up the RLS policies for when the bucket is created via the UI or API.

-- TO OPERATE DOCUMENTS:
-- 1. Create a bucket named 'documents' in the Supabase Storage dashboard.
-- 2. Make the bucket 'Public' (or use private with signed URLs, but 'Public' is easier for this CRM).

-- RLS for Storage (Insert into storage.objects)
-- You may need to run these if you want to restrict storage access to the owner:
CREATE POLICY "Allow authenticated uploads" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'documents');
CREATE POLICY "Allow owners to update their own files" ON storage.objects FOR UPDATE TO authenticated WITH CHECK (bucket_id = 'documents' AND (select auth.uid()::text) = (storage.foldername(name))[1]);
CREATE POLICY "Allow owners to delete their own files" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'documents' AND (select auth.uid()::text) = (storage.foldername(name))[1]);
CREATE POLICY "Allow public read access" ON storage.objects FOR SELECT TO public USING (bucket_id = 'documents');
